### ISSUE TITLE
Integer values are truncated/malformed during encryption

### ISSUE THREAD

**Issue by lukzas** [psecio/secure_dotenv#3]
1. Leading zeros are truncated, `$parser->save('PWD', '012345', true);` results in **12345** after decryption
2. When integer value length is > 19, output is malformed. For `$parser->save('PWD', '1111111111111111111', true);` is fine, but for `$parser->save('PWD', '11111111111111111112', true);` results in **9223372036854775807**, which seems random sequence.

Above holds only for integers, as with at least one string in sequence, it seems to work fine.

**Comment by enygma** [comment]
Hmm, that's a weird one - have you tried updating the version of `defuse/php-encryption` manually to see if the same issue happens? I can't see anything in the code that would cause an issue like that.

**Comment by enygma** [comment]
Ah-hah, I think I see the issue. Somewhere along the line that `11111111111111111112` is getting type-shifted by PHP into an integer. That's why when there's any other value in it besides those numbers it works as expected. The `9223372036854775807` is because `9223372036854775807` is the max int size PHP can handle and `11111111111111111112` is larger than that.

Let me see if there's anything I can do on the side of this lib to help this issue.

**Comment by enygma** [comment]
@lukzas okay, so can you try something for me - pull down the `refactor-ini-lib` branch here and see if you run into the same issue. I couldn't figure out how to get the other library to not do the type switching so I just simplified and made my own "write" function.

Let me know...

**Comment by lukzas** [comment]
@enygma ok, i'll check it out soon

**Comment by lukzas** [comment]
Seems the issue is fixed and it works for all my usual data, you can merge pull request :)
